[tool.poetry]
name = "wiglang"
version = "0.1.0"
description = ""
authors = ["Iainmon <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pyparsing = "^2.4.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
